#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  List by @context:"
  echo "    lsgc"
  echo "      generates a textual report of pending and completed tasks in all projects and contexts"
  echo "      and groups them by the context they belong to."
  echo ""
  exit
}

[ "$action" = "lsgc" ] && {
    # python "`cygpath -w ${TODO_ACTIONS_DIR}/birdseye.py`" "$TODO_FILE" "$DONE_FILE"   
    # python "`cygpath -w ${TODO_ACTIONS_DIR}/birdseye.py`" "`cygpath -w $TODO_FILE`" "`cygpath -w $DONE_FILE`"   
    
	if [ $# -eq 0 ] ; then
	    ${TODO_ACTIONS_DIR}/lsgroup.py "$TODO_FILE" -c
	else
	    echo $1
	    ${TODO_ACTIONS_DIR}/lsgroup.py "$1" -c
	
		# IFS=$'\n'
		# lines=$(/home/sachin/.scripts/todo.sh command lf)
	
		# for l in "${lines[@]}"
		# do
		#   echo "line: $l"
		# done
		
	fi 
}
