#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  List and sort by tag:"
  echo "    lstag"
  echo ""
  exit
}

[ "$action" = "lstag" ] && {
	if [ $# -eq 0 ] ; then
	else
		lines=$(/home/sachin/.scripts/todo.sh command ls | sed -e '/--/d' | sed '/TODO/d')
		for l in "${lines[@]}"
		do
		  echo "line: $l"
		done
	fi 
}
