#!/bin/bash
#
# Shows next actions in each project listed in your projects.txt file

action=$1

function usage {
  echo "    next"
  echo "      Show the next task for each project."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if [[ $action == "next" ]]; then
    for PROJECT in $(sh $TODO_FULL_SH listproj)
    do
       echo "$PROJECT:"
       sh $TODO_FULL_SH ls $PROJECT
       echo
   done
else
    usage
fi
