; ========================================================
;
;
;  $$$$$$\            $$\                               
; $$  __$$\           $$ |                              
; $$ /  \__| $$$$$$\  $$ | $$$$$$\   $$$$$$\   $$$$$$$\ 
; $$ |      $$  __$$\ $$ |$$  __$$\ $$  __$$\ $$  _____|
; $$ |      $$ /  $$ |$$ |$$ /  $$ |$$ |  \__|\$$$$$$\  
; $$ |  $$\ $$ |  $$ |$$ |$$ |  $$ |$$ |       \____$$\ 
; \$$$$$$  |\$$$$$$  |$$ |\$$$$$$  |$$ |      $$$$$$$  |
;  \______/  \______/ \__| \______/ \__|      \_______/ 
;
; 
; Created by Cody Sork
;
;
; ========================================================

; xrdb:color0-15 represents one of 16 colors from a pywal
; theme

[colors]
background = ${xrdb:color0}
foreground = ${xrdb:color15}
accent = ${xrdb:color5}
