; ========================================================
;
;  $$$$$$\                        $$\                             
; $$  __$$\                       $$ |                            
; $$ /  \__|$$\   $$\  $$$$$$$\ $$$$$$\    $$$$$$\  $$$$$$\$$$$\  
; $$ |      $$ |  $$ |$$  _____|\_$$  _|  $$  __$$\ $$  _$$  _$$\ 
; $$ |      $$ |  $$ |\$$$$$$\    $$ |    $$ /  $$ |$$ / $$ / $$ |
; $$ |  $$\ $$ |  $$ | \____$$\   $$ |$$\ $$ |  $$ |$$ | $$ | $$ |
; \$$$$$$  |\$$$$$$  |$$$$$$$  |  \$$$$  |\$$$$$$  |$$ | $$ | $$ |
;  \______/  \______/ \_______/    \____/  \______/ \__| \__| \__|
;
;  
; Created by Cody Sork
;
; ========================================================

; My custom todo.sh script for polybar
; ------------------------------------
; Displays the first "A" priority task from todo.sh
;

[module/todo]
type = custom/script
exec = ~/Scripts/todo/todo.sh -p lsp a | sed "s/[\@].*$//g" | sed "s/^/ /g"
interval = 300
format-padding = 1

[module/calendar]
type= custom/script
exec = calcurse -a | tr '\n-' '\b'  | sed "s/^/ /g"
format-padding = 1 
interval = 300
