; ========================================================
;
;  $$$$$$\                        $$\                             
; $$  __$$\                       $$ |                            
; $$ /  \__|$$\   $$\  $$$$$$$\ $$$$$$\    $$$$$$\  $$$$$$\$$$$\  
; $$ |      $$ |  $$ |$$  _____|\_$$  _|  $$  __$$\ $$  _$$  _$$\ 
; $$ |      $$ |  $$ |\$$$$$$\    $$ |    $$ /  $$ |$$ / $$ / $$ |
; $$ |  $$\ $$ |  $$ | \____$$\   $$ |$$\ $$ |  $$ |$$ | $$ | $$ |
; \$$$$$$  |\$$$$$$  |$$$$$$$  |  \$$$$  |\$$$$$$  |$$ | $$ | $$ |
;  \______/  \______/ \_______/    \____/  \______/ \__| \__| \__|
;
;  
; Created by Cody Sork
;
; ========================================================

[module/calendar]
type= custom/script
exec = calcurse -a | tr '\n-' '\b'  | sed "s/^/ /g"
format-padding = 1 
interval = 300

[module/dmenu]
type= custom/script
exec = /usr/bin/echo 
click-left = /usr/bin/rofi -show combi -hide-scrollbar -kb-row-select "Tab" -kb-row-tab ""

format-background = ${colors.background2}
format-foreground = 000000
format-padding = 1

[module/isw]
type = custom/script
exec = echo 
click-left = sudo isw -b on
click-right = sudo isw -b off
format-padding = 1

[module/optimus]
type=custom/script
exec = ~/.config/polybar/scripts/optimus-status.sh
interval = 3600
format-padding = 1

[module/optimus-menu]
type=custom/menu
interval = 3600
format-padding = 1

label-open = 
label-open-font = 4
label-close = 
label-separator = " / "
label-separator-foreground = ${colors.xcolor1}

; intel
menu-0-0 = "intel"
menu-0-0-exec = /usr/bin/urxvt -e optimus-manager --switch integrated

; nvidia 
menu-0-1 = "nvidia"
menu-0-1-exec = /usr/bin/urxvt -e /usr/bin/optimus-manager --switch nvidia

; hybrid
menu-0-2 = "hybrid"
menu-0-2-exec = /usr/bin/urxvt -e /usr/bin/optimus-manager --switch hybrid

[module/player-cmus]
type = custom/script
exec = ~/.config/polybar/scripts/player-cmus.sh
format-foreground = ${colors.highlight}
interval = 1
click-left = cmus-remote -u &
click-right = cmus-remote -s &
click-middle = cmus-remote -u &

[module/powermenu]
type = custom/menu
format-padding = 1

label-open = 拉
label-open-font = 4
label-close = 
label-separator = " / "
label-separator-foreground = ${colors.xcolor1}

; hibernate
menu-0-0 = 
menu-0-0-exec = systemctl hibernate

; reboot
menu-0-1 = 
menu-0-1-exec = systemctl reboot

; shutdown
menu-0-2 = 
menu-0-2-exec = systemctl poweroff

[module/todo]
type = custom/script
exec = ~/.config/polybar/scripts/current-todo.sh
interval = 5
format-padding = 1

[module/updates-arch-combined]
type = custom/script
exec = ~/.config/polybar/scripts/updates-arch-combined.sh
click-left = /usr/bin/urxvt -e yay -Syu
interval = 3600
format-padding = 1

[module/vpn-anyconnect-status]
type = custom/script
exec = ~/.config/polybar/scripts/vpnstatus.sh
click-left = sudo systemctl start openvpn-client@cody.service
click-middle = sudo systemctl restart openvpn-client@cody.service
click-right = sudo systemctl stop openvpn-client@cody.service
interval = 5
format-padding = 1
