; ========================================================
;
;  $$$$$$\                        $$\                             
; $$  __$$\                       $$ |                            
; $$ /  \__|$$\   $$\  $$$$$$$\ $$$$$$\    $$$$$$\  $$$$$$\$$$$\  
; $$ |      $$ |  $$ |$$  _____|\_$$  _|  $$  __$$\ $$  _$$  _$$\ 
; $$ |      $$ |  $$ |\$$$$$$\    $$ |    $$ /  $$ |$$ / $$ / $$ |
; $$ |  $$\ $$ |  $$ | \____$$\   $$ |$$\ $$ |  $$ |$$ | $$ | $$ |
; \$$$$$$  |\$$$$$$  |$$$$$$$  |  \$$$$  |\$$$$$$  |$$ | $$ | $$ |
;  \______/  \______/ \_______/    \____/  \______/ \__| \__| \__|
;
;  
; Created by Cody Sork
;
; ========================================================

[module/calendar]
type= custom/script
exec = calcurse -a | tr '\n-' '\b'  | sed "s/^/ /g"
format-padding = 1 
interval = 300

[module/info-projecthamster]
type = custom/script
exec = ~/.config/polybar/scripts/info-projecthamster.sh
interval = 60
format-padding = 1

[module/optimus]
type=custom/script
exec = ~/.config/polybar/scripts/optimus-status.sh
interval = 3600
format-underline = ${colors.system}
format-padding = 1

[module/player-cmus]
type = custom/script
exec = ~/.config/polybar/scripts/player-cmus.sh
format-foreground = ${colors.highlight}
interval = 1
click-left = cmus-remote -u &
click-right = cmus-remote -s &
click-middle = cmus-remote -u &

[module/polypomo]
type = custom/script
exec = ~/.config/polybar/scripts/polypomo
tail = true

format-foreground = ${colors.highlight}
label = %output%
click-left = ~/.config/polybar/scripts/polypomo toggle
click-right = ~/.config/polybar/scripts/polypomo end
click-middle = ~/.config/polybar/scripts/polypomo lock
scroll-up = ~/.config/polybar/scripts/polypomo time +60
scroll-down = ~/.config/polybar/scripts/polypomo time -60

[module/total-projecthamster]
type = custom/script
exec = ~/.config/polybar/scripts/total-projecthamster.sh
interval = 60
format-padding = 1

[module/todo]
type = custom/script
exec = ~/.config/polybar/scripts/current-todo.sh
interval = 5
format-padding = 1

[module/updates-arch-combined]
type = custom/script
exec = ~/.config/polybar/scripts/updates-arch-combined.sh
interval = 3600
format-underline = ${colors.network}
format-padding = 1

[module/vpn-anyconnect-status]
type = custom/script
exec = ~/.config/polybar/scripts/vpnstatus.sh
interval = 5
format-underline = ${colors.network}
format-padding-left = 1
